name: Push MinimalRichDomain.SourceGenerators to NuGet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    SOLUTION_PATH: src\\MinimalDomainEvents.sln
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build $SOLUTION_PATH -c Release
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Package
      run: dotnet pack $SOLUTION_PATH -c Release --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json --skip-duplicate